### PR TITLE
Feat: Add auth

### LINKED ISSUE #8: Add authentication guards to pages

### LINKED ISSUE #9: Add authentication to requests sent
Using [axios](https://axios-http.com/docs/intro) or similar to put the access token into the request body. Access token should be stored in the local storage and we should also refresh the token if needed.

### LINKED ISSUE #31: Add login functionality
Building on the UI from #30, add in the functionality to login a user, including showing errors if they occur and appropriately redirecting

### LINKED ISSUE #32: Add register functionality
Building from the UI in #30, build out the register functionality.

### PR DESCRIPTION
**Pull request by sktylr**
Adds authentication to the web app including login, register and logout functionality.
Adds auth guards and context to restrict certain pages and provide information about the user to the components
Adds access tokens to the headers of requests sent using axios and automatic refreshing of the tokens if they have expired

I've kept the styling very basic, if people want to they can update this but I think the bigger area of concern would be getting things like the results pages an bounding box render properly

Closes #9
Closes #8 
Closes #32
Closes #31

### CODE REVIEW

**Comment by Blankumu35** [comment]
At the moment its impossible to sign up. Is there a reason for that?

**Comment by sktylr** [comment]
If you run the back end you should be able to sign up

**Comment by Blankumu35** [comment]
How do i run the backend?

**Comment by sktylr** [comment]
Make sure you have [docker](https://docs.docker.com/get-docker/) installed
```bash
cd ../
git clone https://github.com/ias-tcd/competitor-matching-model.git
cd competitor-matching-model
# On windows there seems to sometimes be an issue with the following line.
# If it doesn't work, create a `.env` file in the root of `competitor-matching-model` and put FRONTEND_URL=http://localhost:5173 in it
echo FRONTEND_URL=http://localhost:5173 >> .env
make build
make run
```
Should work. This will take a while if it's your first time running the back end. If it doesn't work, then we are probably best looking at it in person as it can be fiddly to explain over text.

**Review by temi-oye — APPROVED** [review]
🔥

**Pull request merged**
