### PR TITLE
Update Background of Game and added 7 new brands

### PR DESCRIPTION
**Pull request by Blankumu35**

### CODE REVIEW

**Review by Blankumu35 — COMMENTED** [review]
I also made some changes to the about us page card

**Comment by sktylr** [comment]
Can you add some quick screenshots of the updates?

**Comment by Blankumu35** [comment]
Screenshot 2024-04-08 202827
Screenshot 2024-04-08 222759
Here are pictures of the changes

**Comment by sktylr** [comment]
Great thanks I'll have a look in a mo

**Review by sktylr — APPROVED** [review]

**Pull request merged**
